In [2]:
#QST 01
import numpy as np
na=np.array([[1,2,3],[4,5,6]])
print(na.tolist())

[[1, 2, 3], [4, 5, 6]]


In [7]:
#QST 02
import numpy as np
na=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(na)
trace = np.trace(na)
print(trace)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [3]:
#QST 03
z=2
import numpy as np
a=np.array([[1,8],[3,2]])
2 < a

array([[False,  True],
       [ True, False]])

In [8]:
#QST 04
import numpy as np
na=np.array([[1,8,5],[4,3,6],[9,0,7]])
nb=np.array([[2,6,1],[3,9,5],[0,8,7]])
R=np.add(na, nb)
print(R)

[[ 3 14  6]
 [ 7 12 11]
 [ 9  8 14]]


In [9]:
#QST 05
import numpy as np
na=np.array([[1,8,5],[4,3,6],[9,0,7]])
np.mean(na)

4.777777777777778