In [3]:
import numpy as np
new_array=np.array([1,2,3])
print(new_array)

[1 2 3]


In [4]:
new_array=np.array([[1,2,3],[4,5,6]])
print(new_array)

[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array([(1, 2), (3, 4), (5,6)])
a.shape #3 lignes et 2 colognes, ca renvoi a la composition du vecteur

(3, 2)

In [7]:
a  =np.array([0,0,0,0,1,0,0,0])
print(a)

[0 0 0 0 1 0 0 0]


In [8]:
b = a.reshape(2,4)
print(b) #diviser en2 de sorte qu'on peut le faire de facon a ce que ce soit bien reparti

[[0 0 0 0]
 [1 0 0 0]]


In [13]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a[0,2])

2


In [15]:
print(a[1,:])

[3 4 5]


In [16]:
print(a[:, 2])
print(a[:,-1])

[2 5 8]
[2 5 8]


In [17]:
import numpy as np
value=np.random.random()
print(value)

0.527371185089428


In [18]:
import numpy as np
array=np.random.random((2,2))
print(array)

[[0.09814311 0.25337594]
 [0.00722851 0.67337252]]


In [21]:
import numpy as np
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[2 3 8 2]
 [7 7 6 2]]


In [22]:
array=np.zeros(3)
print(array)

[0. 0. 0.]


In [23]:
array=np.full(3, 5)
print(array)

[5 5 5]


In [24]:
array=np.eye(2)
print(array)

[[1. 0.]
 [0. 1.]]


In [25]:
array=np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [26]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

In [28]:
A=np.add(x, y) #1ere methode
print(A)

[[ 6.  8.]
 [10. 12.]]


In [29]:
A=x+y
print(A) #2eme methode

[[ 6.  8.]
 [10. 12.]]


In [33]:
Z=np.subtract(x, y)

In [34]:
Z=x-y
print(Z)

[[-4. -4.]
 [-4. -4.]]
